### PR TITLE
Code Cleanup

### PR DESCRIPTION
**Pull request by K1ngjulien**
I removed some unused variables and code, added some comments and simplified some things.

Its not much but i hope this helps 😄

### CODE REVIEW

**Comment by K1ngjulien** [comment]
And node updated some of the package details because it was copied into another folder

**Comment by danielflataker** [comment]
I am new to GitHub, and I'm wondering how I can commit to this pull request? I thought I could commit some small changes here, so I don't have to make a new pull request just for code cleanup. Or is that what I am supposed to do?

**Comment by shiffman** [comment]
Hey, this is great! I like these changes but I also should probably have the code match the videos. This is related to #3. Maybe a good solution is to put the code that matches the videos exactly at https://github.com/CodingTrain/website and then have the improvements here?

**Comment by K1ngjulien** [comment]
I agree. this repo is going to contain the monolith bot soon anyway, right?

**Comment by shiffman** [comment]
Ok, now that I have https://github.com/CodingTrain/website/pull/741 I can merge this! Would be good to link to videos and explain differences between this code and the website code in README.

**Pull request merged**
